In [25]:
import cvxpy as cp
import numpy as np

def solve_Welfare_Maximization(L, k, IB_array, b1, TB_array, b2):
    n = L.shape[0]
    S = range(1, n + 1)  # Set of items

    # Decision binary variables
    X = cp.Variable((n, k), boolean=True)    
    # Objective function
    obj = 0
    for i in range(k):
        obj += cp.log_det(cp.diag(X[:,i]) @ L @ cp.diag(X[:,i]))
    obj = cp.Maximize(obj)

    constrains = []
    # Assignment Constraints
    constrains.append(cp.cumsum(X, axis=1)==1)

    # Group Size Constraint
    constrains.append(cp.cumsum(X, axis=0)>=1)

    # Inference Memory Budget Constraint
    constrains.append(IB_array.reshape(1,-1)@X<=b1)

    # Training Time Budget Constraint
    constrains.append(TB_array.reshape(1,-1)@X<=b2)

    # Solve the linear program
    prob = cp.Problem(obj, constrains)
    prob.solve()
    
    # Print the results
    print("The optimal value is", prob.value)
    print("A solution x is")
    print(X.value)

    # # Print the results
    # if sol[0] == 'optimal':
    #     print("\nOptimal Solution:")
    #     for j in range(1, k + 1):
    #         group_items = [i for i in S if sol[1][i - 1 + (j - 1) * n] == 1]
    #         print(f"Group {j}: Items {group_items}")
    # else:
    #     print("No optimal solution found.")


In [26]:
L = np.random.rand(5,5)
L = L@L.T
k=2
IB_array = np.array([1,2,3,4,5])
b1 = 10
TB_array = np.array([1,2,3,4,5])
b2 = 10
solve_Welfare_Maximization(L, k, IB_array, b1, TB_array, b2)

log_det(diag_vec(reshape(var172[0:5, 0], (5,), F), 0) @ [[1.90 0.69 ... 1.99 2.06]
 [0.69 0.37 ... 0.79 0.69]
 ...
 [1.99 0.79 ... 2.56 2.29]
 [2.06 0.69 ... 2.29 2.41]] @ diag_vec(reshape(var172[0:5, 0], (5,), F), 0))
log_det(diag_vec(reshape(var172[0:5, 1], (5,), F), 0) @ [[1.90 0.69 ... 1.99 2.06]
 [0.69 0.37 ... 0.79 0.69]
 ...
 [1.99 0.79 ... 2.56 2.29]
 [2.06 0.69 ... 2.29 2.41]] @ diag_vec(reshape(var172[0:5, 1], (5,), F), 0))


DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
diag_vec(reshape(var172[0:5, 0], (5,), F), 0) @ [[1.90 0.69 ... 1.99 2.06]
 [0.69 0.37 ... 0.79 0.69]
 ...
 [1.99 0.79 ... 2.56 2.29]
 [2.06 0.69 ... 2.29 2.41]] @ diag_vec(reshape(var172[0:5, 0], (5,), F), 0)
diag_vec(reshape(var172[0:5, 1], (5,), F), 0) @ [[1.90 0.69 ... 1.99 2.06]
 [0.69 0.37 ... 0.79 0.69]
 ...
 [1.99 0.79 ... 2.56 2.29]
 [2.06 0.69 ... 2.29 2.41]] @ diag_vec(reshape(var172[0:5, 1], (5,), F), 0)